contact/urls.py
from django.urls import path
from contact import views

app_name='contact'

urlpatterns = [
    path('<int:contact_id>/', views.contact, name='contact'),
    path('search/', views.search, name='search'),
    path('', views.index, name='index'),
    #create
    path('contact/create/', views.create, name="create"),
    #update
    path('contact/<int:contact_id>/update/', views.update, name="update"),
    #delete
    path('contact/<int:contact_id>/delete/', views.delete, name="delete"),

    #URLS USER
    path('user/create/', views.register, name='register'),
    path('user/login/', views.login_view, name='login'),
    path('user/logout/', views.logout_view, name='logout'),
    path('user/update/', views.user_update, name='user_update'),
    
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contact.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

contact/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# id (primary key - automático)
# first_name (string), last_name (string), phone (string)
# email (email), created_date (date), description (text)

# Depois
# category (foreign key), show (boolean), owner (foreign key)
# picture (imagem)


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return f'{self.name}'


class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50)
    email = models.EmailField(max_length=254, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True,upload_to='pictures/%Y/%m/')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

contact/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(
        request, 'contact/index.html'
    )

contact/views/contact_forms.py
from typing import Any, Dict
from django.http import HttpResponse
from django import forms
from django.core.exceptions import ValidationError
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from contact.models import Contact
from django.contrib.auth import password_validation
from django.contrib.auth.decorators import login_required


class ContactForm(forms.ModelForm):    #criando formulario automatico para ser enviado para o template baseado no Model Contact
    picture = forms.ImageField(
        widget=forms.FileInput(attrs={'accept': 'image/*',}),
        required=False
    )
    class Meta:
        model = Contact   #de qual model sera usado
        fields = (   #quais campos serao renderizados
            'first_name', 'last_name', 'phone',
             'email', 'description', 'category','picture',
        )
        widgets = {    #como serao renderizados
            'first_name': forms.TextInput(
                attrs={
                    'class': 'classe-a classe-b',
                    'placeholder': 'Escreva aqui',
                }
            )
        }

    def clean_phone(self):   #validacao do telefone de exemplo, todos os metodos de validação do Django devem iniciar por clean e + nome do campo quando se quer fazer separado
        phone=self.cleaned_data.get('phone')
        if not phone.isdigit() or  not (10 <= len(phone) <= 15):
            raise forms.ValidationError("Este numero nao é um telefone valido",code='invalid')   
        return phone
    
    def clean(self):   #validação quando se usa mais de um campo do post e nao ha problema em fazer junto
        cleaned_data=super().clean()
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')
        errors = {}
        if first_name == "JOAO":
            errors['first_name'] = 'Primeiro nome não pode ser JOAO'
        
        if last_name == "ALMEIDA":
            errors['last_name'] = 'Último nome não pode ser ALMEIDA'
        
        if errors:
            raise forms.ValidationError(errors)
        
        return cleaned_data

@login_required(login_url='contact:login')
def create(request):
    form_action=reverse('contact:create')  #metodo reverse serve para desobrir a url de forma reversa dentro de uma view uma que vez que so da para usar {%url %} nos templates

    if request.method =='POST':
        form=ContactForm(request.POST, request.FILES)
        if form.is_valid():  #verifica se passou nas validaçoes
            contact=form.save(commit=False)
            contact.owner=request.user
            contact.save()
            form_action=reverse('contact:update', kwargs= {"contact_id":contact.pk}) #altera para update
            context = {
            'form': form,
            'site_title': 'Create - ',
            'form_action':form_action
            }
            return redirect('contact:update', contact_id=contact.pk)
        else:
            context = {'form': form,'site_title': 'Create - ', 'form_action': form_action} 
            return render(request,'contact/create.html', context,)
    
    else:   #senao meotodo GET, renderiza a pagina em branco
        context = {
        'form': ContactForm(),
        'site_title': 'Create - ',
        'form_action':form_action
        }

        return render(
        request,
        'contact/create.html', context,)
@login_required(login_url='contact:login')
def update(request, contact_id):
    contact=get_object_or_404(Contact, pk=contact_id, show=True, owner=request.user)
    form_action=reverse('contact:update',args=(contact_id,))  

    if request.method =='POST':
        form=ContactForm(request.POST, request.FILES, instance=contact)
        if form.is_valid():  #verifica se passou nas validaçoes
            context = {
            'form': form,
            'site_title': 'Create - ',
            'form_action':form_action
            }
            contact=form.save()
            return redirect('contact:update', contact_id=contact.pk)
        else:
            context = {'form': form,'site_title': 'Update - ', 'form_action': form_action} 
            return render(request,'contact/create.html', context,)
    
    else:   #senao meotodo GET, renderiza a pagina em branco
        context = {
        'form': ContactForm(instance=contact),
        'site_title': 'Update - ',
        'form_action':form_action
        }

        return render(
        request,
        'contact/create.html', context,)
@login_required(login_url='contact:login')    
def delete(request, contact_id):

    contact = get_object_or_404(
        Contact, pk=contact_id, show=True, owner=request.user
    )
    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        contact.delete()
        return redirect('contact:index')

    return render(
        request,
        'contact/contact.html',
        {
            'contact': contact,
            'confirmation': confirmation,
        }
    )
    
class RegisterForm(UserCreationForm):

    ...
    first_name = forms.CharField(
        required=True,
        min_length=3,
    )
    last_name = forms.CharField(
        required=True,
        min_length=3,
    )
    email = forms.EmailField()

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username', 'password1', 'password2',
        )

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if User.objects.filter(email=email).exists():
            self.add_error(
                'email',
                ValidationError('Já existe este e-mail', code='invalid')
            )

        return email
    
class RegisterUpdateForm(forms.ModelForm):
    first_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.',
        error_messages={
            'min_length': 'Please, add more than 2 letters.'
        }
    )
    last_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.'
    )

    password1 = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
        required=False,
    )

    password2 = forms.CharField(
        label="Password 2",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text='Use the same password as before.',
        required=False,
    )

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username',
        )

    def save(self, commit=True):
        cleaned_data = self.cleaned_data
        user = super().save(commit=False)
        password = cleaned_data.get('password1')

        if password:
            user.set_password(password)

        if commit:
            user.save()

        return user

    def clean(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 or password2:
            if password1 != password2:
                self.add_error(
                    'password2',
                    ValidationError('Senhas não batem')
                )

        return super().clean()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        current_email = self.instance.email

        if current_email != email:
            if User.objects.filter(email=email).exists():
                self.add_error(
                    'email',
                    ValidationError('Já existe este e-mail', code='invalid')
                )

        return email

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        if password1:
            try:
                password_validation.validate_password(password1)
            except ValidationError as errors:
                self.add_error(
                    'password1',
                    ValidationError(errors)
                )

        return password1

contact/views/contact_views.py
from django.shortcuts import redirect, render, get_object_or_404
from contact.models import Contact
from django.http import Http404
from django.db.models import Q
from django.core.paginator  import Paginator


def index(request):
    contacts = Contact.objects.filter(show=True).order_by('id')
    paginator= Paginator(contacts,10)  #Paginação mostra 10 contatos por vez
    page_number= request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj' : page_obj,
        'site_title': 'Contatos - '
    }
    return render(
        request,
        'contact/index.html', context,
    )

def contact(request, contact_id):
   # single_contact = Contact.objects.filter(pk=contact_id,show=True).first()    forma antiga de se fazer 
    single_contact = get_object_or_404(Contact,pk=contact_id, show=True)
    contact_name=f'{single_contact.first_name} { single_contact.last_name} -'
    #if single_contact is None:
    #   raise Http404
    context = {
        'contact' : single_contact,
         'site_title': contact_name
    }
    return render(
        request,
        'contact/contact.html', context,
    )

def search(request):
    search_value= request.GET.get('q','').strip()
    if search_value =='':
        return redirect('contact:index')
    page_obj = Contact.objects.filter(show=True).filter(Q(first_name__icontains=search_value) | Q(last_name__icontains=search_value) | Q(email__icontains=search_value) | Q(phone__icontains=search_value)).order_by('id')
    context = {
        'page_obj' : page_obj,
        'site_title': 'Search - ',
        'search_value':search_value
    }
    return render(
        request,
        'contact/index.html', context,
    )

contact/views/user_forms.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .contact_forms import RegisterForm, RegisterUpdateForm
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth
from django.contrib.auth.decorators import login_required

def register(request):
  form = RegisterForm()

  if request.method=='POST':
    form = RegisterForm(request.POST)
    if form.is_valid():
        name= form.cleaned_data.get('first_name')
        form.save()
        
        messages.success(request, f"O usuario {name} foi registrado")
        return redirect('contact:login')

  
  return render(request, 'contact/register.html',{
    'form': form
  }) 

def login_view(request):
    form = AuthenticationForm(request)
    form_action=reverse('contact:login')
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            messages.success(request, 'Logado com sucesso!')
            return redirect('contact:index')
        messages.error(request, 'Login inválido')

    return render(
        request,
        'contact/login.html',
        {
            'form': form,
             'form_action': form_action
        }
    )


def logout_view(request):
    auth.logout(request)
    return redirect('contact:login')

@login_required(login_url='contact:login')    #decorator para somente acessar essa view se ele estiver logado, caso nao esteja ele redireciona para rota que eu desejar
def user_update(request):
    form = RegisterUpdateForm(instance=request.user)

    if request.method != 'POST':
        return render(
            request,
            'contact/user_update.html',
            {
                'form': form
            }
        )

    form = RegisterUpdateForm(data=request.POST, instance=request.user)

    if not form.is_valid():
        return render(
            request,
            'contact/user_update.html',
            {
                'form': form
            }
        )

    form.save()
    messages.success(request, 'Dados do usuario foram alterados')
    return redirect('contact:index')

contact/templates/contact/contact.html
{% extends "global/base.html" %}

{% block content %}
<div class="single-contact">
    <h1 class="single-contact-name">
       {{contact.first_name}}  {{contact.last_name}}

    </h1>
    <p><b>ID:</b> {{contact.id}}</p>
    <p><b>E-mail:</b> {{contact.email}}</p>
    <p><b>Phone:</b> {{contact.phone}}</p>
    <p><b>Created_Date:</b> {{contact.created_date}}</p>
    <p><b>Description:</b> {{contact.description}}</p>
    <p><b>Category:</b> {{contact.category.name}}</p>
    {% if contact.picture %}
    <p><img src="{{contact.picture.url}}" alt="{{contact.first_name}} {{contact.last_name}}"></p>
    {% endif %}
   
    <div class="contact-links">
        {% if user == contact.owner %}
           <a class="btn btn-link" href="{% url 'contact:update' contact.id %}">Update</a>
        {% endif %}
        <form action="{% url 'contact:delete' contact.id %}" method="POST">
          {% csrf_token %}
          {% if user == contact.owner %}
            {% if confirmation == 'no' %}
              <input type="hidden" name="confirmation" value="yes">
              <button class="btn btn-link btn-delete" type="submit">Confirma?</button>
            {% else %}
              <button class="btn btn-link btn-delete" type="submit">Delete</button>
            {% endif %}
          {% endif %}
        </form>
      </div>
   
    
</div>

{% endblock content %}

contact/templates/contact/create.html
{% extends "global/base.html" %}
{% block content %}
<div class="form-wrapper">
    <h2>CREATE CONTACT</h2>

    <form 
    action="{{form_action}}"   {# a url de envio do form será dinamica pois duas views diferentes vao usar este template a de create e update #}
    method="POST" enctype="multipart/form-data">
    {% csrf_token %}
 
    <div class="form-content">
        {% for field in form %}
        <div class="form-group">
            <label for="{{field.id_for_label}}">{{field.label}}</label>
            {{field}}
            {{field.errors}}
            {{ form.non_field_errors }}
        </div>
        {% if field.name == 'picture' and field.value.url %}
                <div class="form-group">
                    <img src="{{ field.value.url }}" alt="Image of {{ field.name }}">
                </div>
            {% endif %}
        {% endfor %}
    </div>
    <div class="form-content">
        <div class="form-group">
            <button class="btn" type="submit">Send</button>
        </div>
    </div>

    </form>
</div>

{% endblock content %}

contact/templates/contact/index.html
{% extends "global/base.html" %}

{% block content %}
{% if page_obj %}
 <div class="responsive-table">
    <table class="contacts-table">
        <caption class="table-caption">
         Contatcs
        </caption>
        <thead>
            <tr class="table-row table-row-header">
                <th class="table-header">ID</th>
                <th class="table-header">First Name</th>
                <th class="table-header">Last Name</th>
                <th class="table-header">Phone</th>
                <th class="table-header">Email</th>
            </tr>
        </thead>
        <tbody>
            {% for contact in page_obj %}
             <tr class="table-row">
                <td class="table-cel"><a class="table-link" href="{% url "contact:contact" contact.id %}">{{contact.id}}</a></td>
                <td class="table-cel">{{contact.first_name}}</td>
                <td class="table-cel">{{contact.last_name}}</td>
                <td class="table-cel">{{contact.phone}}</td>
                <td class="table-cel">{{contact.email}}</td>
             </tr>  
            {% endfor %}
            
        </tbody>
    </table>
 </div> 
 {% else %}
        <div class="single-contact">
            <h1 class="single-contact-name">Nenhum contato encontrado</h1>
        </div>
 {% endif %}
 {% endblock content %}

contact/templates/contact/login.html
{% extends "global/base.html" %}
{% block content %}
<div class="form-wrapper">
    <h2>Login</h2>
    {% if user.is_authenticated %}
            <p>
                Você fez login como {{ user.username }}.
                Clique <a href="{% url 'contact:logout' %}">aqui</a>
                para sair.
            </p>
            <p>
                Clique <a href="{% url 'contact:user_update' %}">aqui</a>
                para alterar dados do seu usuario.
            </p>
    {% else %}
       {% include "contact/partials/_user-form.html" %}
    {% endif %}

</div>

{% endblock content %}

contact/templates/contact/register.html
{% extends "global/base.html" %}
{% block content %}
<div class="form-wrapper">
    <h2>Register</h2>

   {% include "contact/partials/_user-form.html" %}
</div>

{% endblock content %}

contact/templates/contact/user_update.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">

    <h2>Update User</h2>

    {% include 'contact/partials/_user-form.html' %}
  </div>
{% endblock content %}